Battleground:
    enabled: true
    joinType: Queue
    database: bg
    rated: true
    prefix: "&c[Battleground]&e"
    victoryCondition: highestKills
    matchTime: 60
    nTeams: 4
    teamSize: 1
    defaults:
        options: [woolTeams]
    preReqs:
        options: [clearInventory]
    onEnter:
        options: [storeAll]
    onLeave:
        options: [restoreAll]
    onJoin:
        options: [pvpOff]
    onPrestart:
        options: [pvpOff, teleportIn]
    onStart:
        options: [pvpOn]
    onComplete:
        options: [teleportOut ]
    onSpawn:
        options: [enchants, health=20, hunger=20, deEnchant]
        giveClass:
            default: gladiator
        enchants:
            - speed:3
    onDeath:
        options: [respawn, clearInventory]
    winner:
        options: [enchants, health=20, hunger=20]
        enchants:
            - speed:1:900
            - resistance:1:900
